apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    name: demo
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - image: "nginxdemos/hello"
          name: demo
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "20m"
              memory: "50Mi"
          ports:
            - containerPort: 80
              protocol: TCP